import fs from 'node:fs/promises';import path from 'node:path';import crypto from 'node:crypto';import{execFile}from'node:child_process';import{promisify}from'node:util';import{APP_DIR}from'./config.mjs';const execFileP=promisify(execFile);
const mkid=()=>`cp-${new Date().toISOString().replace(/[:.]/g,'-')}-${crypto.randomBytes(2).toString('hex')}`;const safeRel=(cwd,p)=>{const full=path.resolve(cwd,p),root=path.resolve(cwd);if(full!==root&&!full.startsWith(root+path.sep))throw new Error('Path escapes workspace');return path.relative(root,full).replaceAll('\\','/');};const lines=s=>String(s||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);
export class CheckpointManager{
 constructor(cwd){this.cwd=path.resolve(cwd);this.dir=path.join(APP_DIR,'checkpoints',crypto.createHash('sha1').update(this.cwd).digest('hex').slice(0,10));this.current=null;this.history=[];}
 async init(){await fs.mkdir(this.dir,{recursive:true});return this;}async _git(args,opts={}){try{return(await execFileP('git',args,{cwd:this.cwd,maxBuffer:30_000_000,...opts})).stdout;}catch{return null;}}
 async begin(label='agent turn'){await this.init();const id=mkid(),ref=String(await this._git(['stash','create',`craftcli ${id}`])||'').trim()||String(await this._git(['rev-parse','HEAD'])||'').trim()||null,baselineUntracked=lines(await this._git(['ls-files','--others','--exclude-standard']));this.current={id,label,createdAt:new Date().toISOString(),gitRef:ref,baselineUntracked,gitPaths:[],newUntracked:[],files:{},shellTouched:false};return this.current;}
 async capture(p){if(!this.current)return;const rel=safeRel(this.cwd,p);if(this.current.files[rel])return;const full=path.join(this.cwd,rel);try{this.current.files[rel]={existed:true,data:(await fs.readFile(full)).toString('base64')};}catch(e){if(e.code==='ENOENT')this.current.files[rel]={existed:false,data:null};else throw e;}}
 markShell(){if(this.current)this.current.shellTouched=true;}
 async finish(){if(!this.current)return null;const cp=this.current;this.current=null;if(cp.shellTouched&&cp.gitRef){cp.gitPaths=lines(await this._git(['diff','--name-only',cp.gitRef,'--']));const now=lines(await this._git(['ls-files','--others','--exclude-standard'])),before=new Set(cp.baselineUntracked||[]);cp.newUntracked=now.filter(x=>!before.has(x));}if(!Object.keys(cp.files).length&&!cp.shellTouched)return null;await fs.writeFile(path.join(this.dir,`${cp.id}.json`),JSON.stringify(cp));this.history.push(cp.id);if(this.history.length>30)this.history=this.history.slice(-30);return cp;}
 async latest(){if(this.history.length){const x=this.history.at(-1);try{return JSON.parse(await fs.readFile(path.join(this.dir,`${x}.json`),'utf8'));}catch{}}try{const files=(await fs.readdir(this.dir)).filter(x=>x.endsWith('.json')).sort().reverse();return files[0]?JSON.parse(await fs.readFile(path.join(this.dir,files[0]),'utf8')):null;}catch{return null;}}
 async _restoreGitPath(cp,rel){if(!cp.gitRef)return false;try{await execFileP('git',['cat-file','-e',`${cp.gitRef}:${rel}`],{cwd:this.cwd});const{stdout}=await execFileP('git',['show',`${cp.gitRef}:${rel}`],{cwd:this.cwd,encoding:null,maxBuffer:30_000_000});const full=path.join(this.cwd,rel);await fs.mkdir(path.dirname(full),{recursive:true});await fs.writeFile(full,stdout);return true;}catch{try{await fs.rm(path.join(this.cwd,rel),{force:true});return true;}catch{return false;}}}
 async undoLatest(){const cp=await this.latest();if(!cp)return{ok:false,message:'No checkpoint available.'};let restored=0;const explicit=new Set(Object.keys(cp.files||{}));for(const[rel,snap]of Object.entries(cp.files||{})){const full=path.join(this.cwd,rel);if(snap.existed){await fs.mkdir(path.dirname(full),{recursive:true});await fs.writeFile(full,Buffer.from(snap.data,'base64'));}else await fs.rm(full,{force:true}).catch(()=>{});restored++;}for(const rel of cp.gitPaths||[]){if(!explicit.has(rel)&&await this._restoreGitPath(cp,rel))restored++;}for(const rel of cp.newUntracked||[]){if(!explicit.has(rel)){await fs.rm(path.join(this.cwd,rel),{recursive:true,force:true}).catch(()=>{});restored++;}}if(this.history.at(-1)===cp.id)this.history.pop();await fs.rm(path.join(this.dir,`${cp.id}.json`),{force:true}).catch(()=>{});return{ok:true,id:cp.id,restored,shellTouched:!!cp.shellTouched,message:`Restored ${restored} path${restored===1?'':'s'} from ${cp.id}${cp.shellTouched?' (Git index/staging changes may still need review)':''}.`};}
}
