import fs from 'node:fs/promises';
import path from 'node:path';
function safePath(cwd,p){const full=path.resolve(cwd,p),root=path.resolve(cwd);if(full!==root&&!full.startsWith(root+path.sep))throw new Error('Path escapes workspace');return full;}
function clip(s,n){s=String(s??'');return s.length>n?s.slice(0,n)+`\n… clipped ${s.length-n} chars`:s;}
export class FileReferenceIndex{
 constructor(cwd,{ignore=[],maxFiles=6000,maxAttachChars=24000,maxTotalAttachChars=60000}={}){Object.assign(this,{cwd:path.resolve(cwd),ignore:new Set(ignore),maxFiles,maxAttachChars,maxTotalAttachChars});this.files=[];}
 async scan(){const out=[];const walk=async dir=>{if(out.length>=this.maxFiles)return;let entries=[];try{entries=await fs.readdir(dir,{withFileTypes:true});}catch{return;}for(const e of entries){if(out.length>=this.maxFiles)break;if(this.ignore.has(e.name))continue;const full=path.join(dir,e.name),rel=path.relative(this.cwd,full).replaceAll('\\','/');if(e.isDirectory())await walk(full);else if(e.isFile())out.push(rel);}};await walk(this.cwd);this.files=out.sort((a,b)=>a.localeCompare(b));return this.files;}
 suggest(query='',limit=8){const q=String(query).toLowerCase();if(!q)return this.files.slice(0,limit);const a=[],b=[];for(const f of this.files){const x=f.toLowerCase();if(x.startsWith(q))a.push(f);else if(x.includes(q))b.push(f);if(a.length+b.length>=limit*4)break;}return[...a,...b].slice(0,limit);}
 refsIn(text){const refs=[],re=/(^|\s)@([A-Za-z0-9_./\\-]+)/g;let m;while((m=re.exec(String(text)))!==null){const raw=m[2].replaceAll('\\','/');if(this.files.includes(raw)&&!refs.includes(raw))refs.push(raw);}return refs;}
 async expand(text){const refs=this.refsIn(text);if(!refs.length)return{prompt:text,refs:[],warnings:[]};let total=0;const blocks=[],warnings=[];for(const rel of refs){if(total>=this.maxTotalAttachChars){warnings.push(`Skipped @${rel}: attachment budget reached`);continue;}try{const full=safePath(this.cwd,rel),stat=await fs.stat(full);if(stat.size>2_000_000){warnings.push(`Skipped @${rel}: file is larger than 2 MB`);continue;}const raw=await fs.readFile(full,'utf8'),room=Math.min(this.maxAttachChars,this.maxTotalAttachChars-total),body=clip(raw,room);total+=body.length;blocks.push(`<file_reference path="${rel}">\n${body}\n</file_reference>`);}catch(e){warnings.push(`Could not attach @${rel}: ${e.message}`);}}return{prompt:`${text}\n\nAttached file references (user-selected):\n${blocks.join('\n\n')}`,refs,warnings};}
}
